### ISSUE TITLE
[Add] New tool "Figma" 

### ISSUE THREAD

**Issue by singodiyashubham87** [Miniato-Office/awesome-chrome-extensions#10]
I want to add a new tool "Figma" under the productivity category.

**Comment by RashakDude** [comment]
Hi @singodiyashubham87 You can start with the issue

**Comment by singodiyashubham87** [comment]
Mistakenly I have merged the PR, You can remove the last commit.

**Comment by RashakDude** [comment]
Requesting you to look at the link. Looks like link is broken. @singodiyashubham87 
Also, please keep the description short. Thanks :)

**Comment by RashakDude** [comment]
Closing this as resolved in #15
