### ISSUE TITLE
Add Buster: Captcha Solver for Humans

### ISSUE THREAD

**Issue by Ahlyab** [Miniato-Office/awesome-chrome-extensions#11]
I want to add buster chrome extension to this collection, it solves captcha automatically

**Comment by RashakDude** [comment]
Hi @Ahlyab Please start with the issue

**Comment by Ahlyab** [comment]
Hi @RashakDude I want to ask if I should put this extension in AI powered section or productivity section?

**Comment by RashakDude** [comment]
Hi @Ahlyab, I guess this should go in AI powered section. What do you think ?

**Comment by Ahlyab** [comment]
Hi @RashakDude I agree with you but basically it's main purpose it to enhance productivity so I think it can be placed in either of the two categories

**Comment by Ahlyab** [comment]
@RashakDude Sir kindly let me know if I need to shift it to AI Powered Section

**Comment by RashakDude** [comment]
It's okay @Ahlyab. You can add it in productivity section. Merging your PR.

**Comment by RashakDude** [comment]
Closing this as merged at #12
