### ISSUE TITLE
Add color zilla

### ISSUE THREAD

**Issue by Ahlyab** [Miniato-Office/awesome-chrome-extensions#24]
ColorZilla is the most user friendly, full-featured, secure and reliable color picker and color related suite of tools. It is one of the most popular Chrome and Firefox developer extensions with over 10 million downloads worldwide.

**Comment by Ahlyab** [comment]
@RashakDude kindly assign this to me

**Comment by RashakDude** [comment]
Please go ahead @Ahlyab

**Comment by RashakDude** [comment]
Closing this as resolved in #25
